# Generated by Django 5.1.5 on 2025-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='item_images/'),
        ),
    ]
